# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 05:01
from __future__ import unicode_literals

import tagging.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
